apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    app: demo-app-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      name: nginx-app
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app-port
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"