apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-readiness-deployment
spec:
  selector:
    matchLabels:
      app: liveness-readiness-label
  template:
    metadata:
      labels:
        app: liveness-readiness-label
    spec:
      containers:
      - name: liveness-readiness-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: nginx-port
        readinessProbe:
          httpGet:
            path: /
            port: nginx-port
          initialDelaySeconds: 10
          timeoutSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: nginx-port
            scheme: HTTP
          timeoutSeconds: 30
          initialDelaySeconds: 15
