apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-app
spec:
  replicas: 3
  selector:
    app: rc-label
  template:
    metadata:
      labels:
        app: rc-label
    spec:
      containers:
        - name: rc-demo
          image: nginx
          ports:
            - containerPort: 80
