apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: app
        image: wordpress
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: wp-port
          containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1:3306
          - name: WORDPRESS_DB_USER
            value: exampleuser
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: wp-secrets
          - name: WORDPRESS_DB_NAME
            value: exampledb
      - name: db
        image: mysql:5.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MYSQL_DATABASE
            value: exampledb
          - name: MYSQL_USER
            value: exampleuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: wp-secrets
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: '1'
        ports:
        - name: mysql-port
          containerPort: 3306
