apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-app
spec:
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
        - name: healthcheck
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: app-port
          livenessProbe:
            httpGet:
              path: /
              port: app-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
