apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume-app
spec:
  selector:
    matchLabels:
      app: secret-volume
  template:
    metadata:
      labels:
        app: secret-volume
    spec:
      containers:
        - name: secret-volume
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cred-volume
              mountPath: /etc/creds
              readOnly: true
      volumes:
        - name: cred-volume
          secret:
            secretName: mysecret
