apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    resources: {}
    volumeMounts:
    - name: demo-vol
      mountPath: /tmp
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: demo-vol
    emptyDir: {}
status: {}
