apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-world-rc
spec: 
  replicas: 3
  selector:
    app: helloworld 
  template: 
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
