apiVersion: v1
kind: Pod
metadata:
  name: secbusybox
spec:
  securityContext:
    runAsUser: 3000
    runAsGroup: 4000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 3600" ]
    securityContext:
      runAsUser: 2000
      runAsGroup: 1000
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
