apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: nginx
    name: sidecar-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: local-vol
      mountPath: usr/share/nginx/html
    resources: {}
  - image: busybox
    name: main-container
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Hi I am from Main container' >> /var/log/index.html; sleep 5;done"]
    resources: {}
    volumeMounts:
    - name: local-vol
      mountPath: /var/log
  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: local-vol
    emptyDir: {}
status: {}
